#!/usr/bin/python
import os
import time
import traceback
import requests
from hosted import config, api, node


def cleanup(max_age=12*3600):
    # very useful thank you info-beamer devs
    now = time.time()
    for filename in os.listdir("."):
        if not filename.startswith('cache-'):
            continue
        age = now - os.path.getctime(filename)
        if age > max_age:
            try:
                os.unlink(filename)
            except:
                traceback.print_exc()

def main():
    config.restart_on_update()

    while 1:
        try:
            cleanup()
            # get number of dad jokes 
            dadjokes = []
            for i in range(config.count):
                joke_json = requests.get(headers="Accept": "application/json", url=config.url)
                dadjokes.append(joke_json)
 
            # write to file
            node.write_json("dadjokes.json", dadjokes)
        except:
            traceback.print_exc()
            time.sleep(60)
        else:
            time.sleep(60 * config.poll_interval)

if __name__ == '__main__':
    main()
