#!/usr/bin/python
import os
import sys
import time
import traceback
from unicodedata import name
import requests
from hosted import config, node


def cleanup(max_age=12*3600):
    # very useful thank you info-beamer devs
    now = time.time()
    for filename in os.listdir("."):
        if not filename.startswith('cache-'):
            continue
        age = now - os.path.getctime(filename)
        if age > max_age:
            try:
                os.unlink(filename)
            except:
                traceback.print_exc()

def main():
    config.restart_on_update()
    while 1:
        try:
            # clean older files
            cleanup()
            # get number of dad jokes 
            dadjokes = {}
            for i in range(config.count):
                joke_json = requests.get(headers={'Accept': 'application/json'}, url='https://icanhazdadjoke.com/').json()
                
                husk = {
                    'joke': joke_json['joke']
                }
                dadjokes[i] = husk
            print >>sys.stderr, 'caching %s' % dadjokes
            # write to file
            node.write_json("dadjokes.json", dadjokes)
        except:
            traceback.print_exc()
            time.sleep(60)
        else:
            time.sleep(60 * config.poll_interval)

if __name__ == '__main__':
    main()
