#!/usr/bin/python
import os
import time
import traceback
import requests
from hosted import config, node


def cleanup(max_age=12*3600):
    # very useful thank you info-beamer devs
    now = time.time()
    for filename in os.listdir("."):
        if not filename.startswith('cache-'):
            continue
        age = now - os.path.getctime(filename)
        if age > max_age:
            try:
                os.unlink(filename)
            except:
                traceback.print_exc()

def main():
    config.restart_on_update()
    with open(file='logg.log', mode='a') as log:
        log.write("opened\n")
        while 1:
            log.write("while\n")
            try:
                log.write("try\n")
                # clean older files
                cleanup()
                log.write("cleaned\n")

                # get number of dad jokes 
                dadjokes = []
                for i in range(config.count):
                    joke_json = requests.get(headers={'content-type': 'application/json'}, url='https://icanhazdadjoke.com/')
                    dadjokes.append(joke_json)
                    log.write("load joke number: "+i+"\n")

                log.write("write to json\n")
                # write to file
                node.write_json("dadjokes.json", dadjokes)
                log.write("saved\n")
            except:
                traceback.print_exc()
                time.sleep(60)
            else:
                time.sleep(60 * config.poll_interval)

if __name__ == '__main__':
    main()
